//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPBSv11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DPBSv11Entities1 : DbContext
    {
        public DPBSv11Entities1()
            : base("name=DPBSv11Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_AGENDA> TB_AGENDA { get; set; }
        public virtual DbSet<TB_AGENDAMENTO> TB_AGENDAMENTO { get; set; }
        public virtual DbSet<TB_CATEGORIA> TB_CATEGORIA { get; set; }
        public virtual DbSet<TB_CLIENTE> TB_CLIENTE { get; set; }
        public virtual DbSet<TB_FUNCAO> TB_FUNCAO { get; set; }
        public virtual DbSet<TB_FUNCIONARIO> TB_FUNCIONARIO { get; set; }
        public virtual DbSet<TB_PROMOCAO> TB_PROMOCAO { get; set; }
        public virtual DbSet<TB_SERVICO> TB_SERVICO { get; set; }
    }
}
