//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPBSv11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_AGENDAMENTO
    {

        [Display(Name = "Código")]
        public int COD_AGENDAMENTO { get; set; }

        [Display(Name = "Data")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataBrasil(ErrorMessage = "Data inválida", DataRequerida = false)]
        public System.DateTime DATA { get; set; }
        [Display(Name = "Hora")]
        [DisplayFormat(DataFormatString = "{0:HH:mm:ss}", ApplyFormatInEditMode = true)]
        [DataBrasil(ErrorMessage = "Data inválida", DataRequerida = false)]
        public System.DateTime HORA { get; set; }
        public Nullable<int> COD_AGENDA { get; set; }
        [Display(Name = "Funcionário")]
        public int COD_FUNCIONARIO { get; set; }
        [Display(Name = "Serviço")]
        public int COD_SERVICO { get; set; }
        [Display(Name = "Cliente")]
        public int COD_CLIENTE { get; set; }
        [Display(Name = "Situação")]
        public string SITUACAO { get; set; }
        [Display(Name = "Motivo do cancelamento")]

        public string MOTIVO_CANCELAMENTO { get; set; }

        public virtual TB_AGENDA TB_AGENDA { get; set; }
        public virtual TB_CLIENTE TB_CLIENTE { get; set; }
        public virtual TB_FUNCIONARIO TB_FUNCIONARIO { get; set; }
        public virtual TB_SERVICO TB_SERVICO { get; set; }
    }
}
