//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPBSv11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_AGENDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_AGENDA()
        {
            this.TB_AGENDAMENTO = new HashSet<TB_AGENDAMENTO>();
        }

        [Display(Name = "Código")]
        public int COD_AGENDA { get; set; }
        [Display(Name = "Data")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataBrasil(ErrorMessage = "Data inválida", DataRequerida = false)]
        public Nullable<System.DateTime> DATA { get; set; }
        [Display(Name = "Hora")]
        [DisplayFormat(DataFormatString = "{0:HH:mm:ss}", ApplyFormatInEditMode = true)]
        [DataBrasil(ErrorMessage = "Data inválida", DataRequerida = false)]
        public Nullable<System.DateTime> HORA { get; set; }
        [Display(Name = "Funcionário")]
        public Nullable<int> COD_FUNCIONARIO { get; set; }
        [Display(Name = "Serviço")]
        public Nullable<int> COD_SERVICO { get; set; }
        [Display(Name = "Situação")]
        public string SITUACAO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AGENDAMENTO> TB_AGENDAMENTO { get; set; }
        public virtual TB_FUNCIONARIO TB_FUNCIONARIO { get; set; }
        public virtual TB_SERVICO TB_SERVICO { get; set; }
    }
}
