//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPBSv11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLIENTE()
        {
            this.TB_AGENDAMENTO = new HashSet<TB_AGENDAMENTO>();
        }

        public int COD_CLIENTE { get; set; }
        [Display(Name = "Data")]
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        [Display(Name = "Nome Cliente")]
        public string NOME { get; set; }
        [Display(Name = "CPF")]
        [CustomValidationCPF(ErrorMessage = "CPF inválido")]
        public string CPF { get; set; }
        [Display(Name = "E-mail")]
        //[EmailBrasil(EmailRequerido = true)]
        //[EmailAddress(ErrorMessage = "E-mail em formato inválido.")]
        public string EMAIL { get; set; }
        [Display(Name = "Senha")]
        //[SenhaBrasil(SenhaForteRequerida = true, SenhaTamanhoMaximo = 8, SenhaTamanhoMinimo = 6)]
        public string SENHA { get; set; }
        [Display(Name = "Telefone")]
        public string TELEFONE { get; set; }
        [Display(Name = "Acesso")]
        public string ACESSO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AGENDAMENTO> TB_AGENDAMENTO { get; set; }
    }
}
