//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPBSv11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_FUNCIONARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_FUNCIONARIO()
        {
            this.TB_AGENDAMENTO = new HashSet<TB_AGENDAMENTO>();
            this.TB_SERVICO = new HashSet<TB_SERVICO>();
            this.TB_AGENDA = new HashSet<TB_AGENDA>();
        }

        public int COD_FUNCIONARIO { get; set; }
        [Display(Name = "Data")]
        public Nullable<System.DateTime> DATA_CAD { get; set; }
        [Display(Name = "Nome Funcionário")]
        public string NOME { get; set; }
        [Display(Name = "CPF")]
        [CustomValidationCPF(ErrorMessage = "CPF inválido")]
        public string CPF { get; set; }
        [Display(Name = "E-mail")]

        public string EMAIL { get; set; }
        [Display(Name = "Senha")]

        public string SENHA { get; set; }
        [Display(Name = "Função")]
        public Nullable<int> COD_FUNCAO { get; set; }
        [Display(Name = "Acesso")]
        public string ACESSO { get; set; }
        [Display(Name = "Situação")]
        public string SITUACAO { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AGENDAMENTO> TB_AGENDAMENTO { get; set; }
        public virtual TB_FUNCAO TB_FUNCAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SERVICO> TB_SERVICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AGENDA> TB_AGENDA { get; set; }
    }
}
