//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPBSv11.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TB_PROMOCAO
    {
        [Display(Name = "Código")]
        public int COD_PROMOCAO { get; set; }
        [Display(Name = "Serviço em promoção")]
        public Nullable<int> COD_SERVICO { get; set; }
        [Display(Name = "Descrição")]
        public string DESCRICAO { get; set; }
        [Display(Name = "Valor")]
        [NumeroBrasil(ErrorMessage = "Valor inválido", DecimalRequerido = false)]
        public decimal VALOR { get; set; }
        [Display(Name = "Inicio")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime DATA_INI { get; set; }
        [Display(Name = "Fim")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DataBrasil(ErrorMessage = "Data inválida", DataRequerida = false)]
        public System.DateTime DATA_FIM { get; set; }

        public virtual TB_SERVICO TB_SERVICO { get; set; }
    }
}
