--USE MASTER
--DROP DATABASE DPBSv2

DROP DATABASE DPBSv11
CREATE DATABASE DPBSv11
GO

USE DPBSv11;
GO
--------------------------------------------------------------------
CREATE TABLE TB_CLIENTE (COD_CLIENTE INT NOT NULL IDENTITY(1,1),
					     DATA_CAD DATETIME , 
					     NOME VARCHAR(50) NOT NULL, 
					     CPF CHAR(11) NOT NULL, 
					     EMAIL VARCHAR(50) NOT NULL, 
					     SENHA VARCHAR(32) NOT NULL,
					     TELEFONE VARCHAR(11) NOT NULL,
						 ACESSO VARCHAR(20)  DEFAULT  'CLIENTE'
CONSTRAINT PK_CLIENTE_COD_CLIENTE PRIMARY KEY(COD_CLIENTE),
CONSTRAINT UN_CLIENTE_CPF UNIQUE (CPF),
CONSTRAINT UN_CLIENTE_EMAIL UNIQUE (EMAIL));
GO
--------------------------------------------------------------------

INSERT INTO [TB_CLIENTE] (DATA_CAD, NOME, CPF, EMAIL, SENHA, TELEFONE) VALUES ('20/05/2019','CRISTIANO','12345678910','CRISTIANO@GMAIL.COM','123456','11999999999')
--------------------------------------------------------------------
CREATE TABLE TB_FUNCAO (COD_FUNCAO INT NOT NULL IDENTITY(1,1),
					    FUNCAO VARCHAR(20) NOT NULL,
CONSTRAINT PK_FUNCAO_COD_FUNCAO PRIMARY KEY(COD_FUNCAO));
GO
					
INSERT INTO TB_FUNCAO VALUES ('GERENTE')
INSERT INTO TB_FUNCAO VALUES ('BARBEIRO')

GO
--------------------------------------------------------------------
CREATE TABLE TB_FUNCIONARIO (COD_FUNCIONARIO INT NOT NULL IDENTITY(1,1), 
						     DATA_CAD DATETIME,
                             NOME VARCHAR(50) NOT NULL, 
						     CPF CHAR(11) NOT NULL, 
						     EMAIL VARCHAR(50) NOT NULL,
						     SENHA VARCHAR(32) NOT NULL,
						     COD_FUNCAO INT,
							 ACESSO VARCHAR (20) NOT NULL, 
						     SITUACAO VARCHAR(1) DEFAULT '1',
CONSTRAINT PK_FUNCIONARIO_COD_FUNCIONARIO PRIMARY KEY(COD_FUNCIONARIO),
CONSTRAINT UN_FUNCIONARIO_CPF UNIQUE (CPF),
CONSTRAINT UN_FUNCIONARIO_EMAIL UNIQUE (EMAIL),
CONSTRAINT FK_FUNCIONARIO_COD_FUNCAO FOREIGN KEY(COD_FUNCAO) REFERENCES TB_FUNCAO (COD_FUNCAO),
CONSTRAINT CK_FUNCIONARIO_SITUACAO CHECK (SITUACAO IN ('1','0')),
CONSTRAINT CK_FUNCIONARIO_ACESSO CHECK (ACESSO IN ('ADMINISTRADOR','FUNCIONARIO')));
GO

INSERT INTO TB_FUNCIONARIO VALUES ('27/05/2019','CRISTIANO','12345678910','CRISTIANO@GMAIL.COM',123456,1,'ADMINISTRADOR',1)
INSERT INTO TB_FUNCIONARIO VALUES ('27/05/2019','LEANDRO','12345678911','LEANDRO@GMAIL.COM',123456,1,'ADMINISTRADOR',1)
INSERT INTO TB_FUNCIONARIO VALUES ('27/05/2019','THOMAS','12345678912','THOMAS@GMAIL.COM',123456,1,'ADMINISTRADOR',1)
INSERT INTO TB_FUNCIONARIO VALUES ('27/05/2019','VINICIUS','12345678913','VINICIUS@GMAIL.COM',123456,1,'ADMINISTRADOR',1)
INSERT INTO TB_FUNCIONARIO VALUES ('27/05/2019','ZÉ','12345678914','ZE@GMAIL.COM',123456,1,'ADMINISTRADOR',1)

GO
--------------------------------------------------------------------
CREATE TABLE TB_SERVICO (COD_SERVICO INT NOT NULL IDENTITY(1,1), 
					     SERVICO VARCHAR(30)NOT NULL,
					     VALOR DECIMAL(6) NOT NULL,
					     COD_PROMOCAO INT,
					     COD_FUNCIONARIO INT,
CONSTRAINT PK_SERVICO_COD_SERVICO PRIMARY KEY(COD_SERVICO),
CONSTRAINT FK_SERVICO_COD_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO));
GO					 

INSERT INTO TB_SERVICO VALUES ('CORTE', 25.0,1,1)
INSERT INTO TB_SERVICO VALUES ('BARBA', 30.0,1,1)
INSERT INTO TB_SERVICO VALUES ('CORTE + BARBA', 55.0,1,1)
GO
--------------------------------------------------------------------
CREATE TABLE TB_PROMOCAO (COD_PROMOCAO INT NOT NULL IDENTITY(1,1),
					      COD_SERVICO INT,
			              DESCRICAO VARCHAR (100) NOT NULL,
					      VALOR DECIMAL(6) NOT NULL,
	                      DATA_INI DATE NOT NULL, 
					      DATA_FIM DATE NOT NULL,
CONSTRAINT PK_PROMOCAO_COD_PROMOCAO PRIMARY KEY(COD_PROMOCAO),
CONSTRAINT FK_PROMOCAO_COD_SERVICO FOREIGN KEY(COD_SERVICO) REFERENCES TB_SERVICO (COD_SERVICO));
GO

INSERT INTO TB_PROMOCAO VALUES (1,'CORTE + BARBA',50.0,'27/05/2019','30/06/2019')
GO
--------------------------------------------------------------------
CREATE TABLE TB_CATEGORIA (COD_CATEGORIA INT NOT NULL IDENTITY(1,1),
					       CATEGORIA VARCHAR(30) NOT NULL,
					       COD_SERVICO INT,
CONSTRAINT PK_CATEGORIA_COD_CATEGORIA PRIMARY KEY(COD_CATEGORIA),
CONSTRAINT FK_CATEGORIA_COD_SERVICO FOREIGN KEY(COD_SERVICO) REFERENCES TB_SERVICO (COD_SERVICO));
GO

INSERT INTO TB_CATEGORIA VALUES ('ADULTO',1)
INSERT INTO TB_CATEGORIA VALUES ('INFANTIL',1)
GO
--------------------------------------------------------------------
CREATE TABLE TB_AGENDA (COD_AGENDA INT NOT NULL IDENTITY(1,1),
	                         DATA DATETIME,
						     HORA DATETIME,
						     COD_FUNCIONARIO INT,
						     COD_SERVICO INT,
						     SITUACAO VARCHAR(1) DEFAULT '1',
CONSTRAINT PK_AGENDA_COD_AGENDA PRIMARY KEY(COD_AGENDA),
CONSTRAINT FK_AGENDA_COD_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO),
CONSTRAINT FK_AGENDA_COD_SERVICO FOREIGN KEY(COD_SERVICO) REFERENCES TB_SERVICO (COD_SERVICO),
);
GO						 

INSERT INTO TB_AGENDA VALUES ('10/06/2019','08:00',1,1,1)
INSERT INTO TB_AGENDA VALUES ('10/06/2019','08:30',1,1,1)
INSERT INTO TB_AGENDA VALUES ('10/06/2019','09:00',1,1,1)
INSERT INTO TB_AGENDA VALUES ('10/06/2019','09:30',1,1,1)
GO
-----------------------------------------------------------------------------------------------------------
CREATE TABLE TB_AGENDAMENTO (COD_AGENDAMENTO INT NOT NULL IDENTITY(1,1),
	                         DATA DATETIME NOT NULL,
						     HORA DATETIME NOT NULL,
							 COD_AGENDA INT,
						     COD_FUNCIONARIO INT NOT NULL,
						     COD_SERVICO INT NOT NULL,
						     COD_CLIENTE INT NOT NULL,
						     SITUACAO VARCHAR(1) DEFAULT '1',
							 MOTIVO_CANCELAMENTO VARCHAR(500),
							
CONSTRAINT PK_AGENDAMENTO_COD_AGENDAMENTO PRIMARY KEY(COD_AGENDAMENTO),
CONSTRAINT FK_AGENDAMENTO_COD_FUNCIONARIO FOREIGN KEY(COD_FUNCIONARIO) REFERENCES TB_FUNCIONARIO (COD_FUNCIONARIO),
CONSTRAINT FK_AGENDAMENTO_COD_SERVICO FOREIGN KEY(COD_SERVICO) REFERENCES TB_SERVICO (COD_SERVICO),
CONSTRAINT FK_AGENDAMENTO_COD_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES TB_CLIENTE (COD_CLIENTE),
CONSTRAINT FK_AGENDA FOREIGN KEY(COD_AGENDA) REFERENCES TB_AGENDA (COD_AGENDA));
GO						 

INSERT INTO TB_AGENDAMENTO VALUES ('10/06/2019','08:00',1,1,1,1,1, 'IREI VIAJAR E NÃO PODEREI COMPARECER NA DATA AGENDADA')
INSERT INTO TB_AGENDAMENTO VALUES ('10/06/2019','08:30',1,1,1,1,1, 'IREI VIAJAR E NÃO PODEREI COMPARECER NA DATA AGENDADA')
INSERT INTO TB_AGENDAMENTO VALUES ('10/06/2019','09:00',1,1,1,1,1, 'IREI VIAJAR E NÃO PODEREI COMPARECER NA DATA AGENDADA')
INSERT INTO TB_AGENDAMENTO VALUES ('10/06/2019','09:30',1,1,1,1,1, 'IREI VIAJAR E NÃO PODEREI COMPARECER NA DATA AGENDADA')
GO
--------------------------------------------------------------------
--CREATE TABLE TB_ESTILO (COD_ESTILO INT NOT NULL IDENTITY(1,1),
--					    CORTE VARCHAR(50)NOT NULL,
--					    DESCRICAO VARCHAR(1000),
--					    IMAGEM NVARCHAR(MAX)
--CONSTRAINT PK_ESTILO_COD_ESTILO PRIMARY KEY (COD_ESTILO))

--INSERT INTO TB_ESTILO (CORTE,DESCRICAO,IMAGEM)  SELECT 'Barba','Barba lenhador',BulkColumn FROM OPENROWSET(BULK N'C:\Barba.jpg', SINGLE_BLOB) IMAGEM 
--INSERT INTO TB_ESTILO (CORTE,DESCRICAO,IMAGEM)  SELECT 'Barba','Barba lenhador',BulkColumn FROM OPENROWSET(BULK N'C:\Cabelo1.jpg', SINGLE_BLOB) IMAGEM 
--INSERT INTO TB_ESTILO (CORTE,DESCRICAO,IMAGEM)  SELECT 'Barba','Barba lenhador',BulkColumn FROM OPENROWSET(BULK N'C:\Barba4.jpg', SINGLE_BLOB) IMAGEM 
--INSERT INTO TB_ESTILO (CORTE,DESCRICAO,IMAGEM)  SELECT 'Barba','Barba lenhador',BulkColumn FROM OPENROWSET(BULK N'C:\Barba5.jpg', SINGLE_BLOB) IMAGEM 

--update TB_ESTILO set IMAGEM = (SELECT BulkColumn FROM OPENROWSET(BULK N'C:\Barba.jpg', SINGLE_BLOB) IMAGEM) WHERE COD_ESTILO = 1









--------------------------------------------------------------------
SELECT * FROM TB_CLIENTE;
SELECT * FROM TB_FUNCIONARIO;
SELECT * FROM TB_FUNCAO;
SELECT * FROM TB_SERVICO;
SELECT * FROM TB_PROMOCAO;
SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_AGENDAMENTO  
SELECT * FROM TB_AGENDA;


--DROP TABLE TB_ESTILO;
--DROP TABLE TB_AGENDAMENTO;
--DROP TABLE TB_CATEGORIA;
--DROP TABLE TB_PROMOCAO;
--DROP TABLE TB_SERVICO;
--DROP TABLE TB_FUNCIONARIO;
--DROP TABLE TB_FUNCAO;
--DROP TABLE TB_CLIENTE;
--DELETE FROM TB_LOGINCLIENTE;

